services:
  backend:
    build: ./backend
    volumes:
      - backend_data:/app
    env_file: .env
    environment:
      - APP_AUTH_CLIENT_ID
      - APP_AUTH_CLIENT_SECRET
      - APP_AUTH_REDIRECT_URI
      - APP_DB_HOST
      - APP_DB_PORT
      - APP_DB_NAME
      - APP_DB_USER
      - APP_DB_PASSWORD
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  backend_data:
